### ISSUE TITLE
Can't download ITV or BBC shows

### ISSUE THREAD

**Issue by BritTVfan** [Ascoware/get-iplayer-automator#224]
**This issue tracker is not a discussion forum, so don't use it as such.  If you wish to discuss the BBC, iPlayer or anything else that is not related to an actual problem with the current release of GiA, post in an appropriate forum, not in this issue tracker.**

**STOP! DO NOT submit a ticket if you are reporting that you are unable to download a program from outside the UK**.

If you need an explanation, read [this](https://github.com/Ascoware/get-iplayer-automator/wiki/No-Support-for-GiA-Outside-the-UK). If you ignore this instruction, your ticket will be closed with no further action. You can fib about your location if you like, but you will only be wasting your time. If you are using GiA within the UK, continue with the instructions below.

Before creating a new ticket, search the current open and closed tickets to see if your issue has already been reported. Use the search box at the top of the page to do so. You can also use the links below to view open and closed tickets in list form.

#### [Closed tickets](https://github.com/Ascoware/get-iplayer-automator/issues?q=is%3Aissue+is%3Aclosed)

If you create a ticket for an issue that has already been reported, your ticket will be closed with no further action. If you are certain your issue has not yet been reported, continue with the instructions below.

Create a succinct title describing your issue in the `Title` field above, then provide the information requested below. If you do not provide the requested information, your ticket will be closed with no further action.

If you cannot download a program, provide a verbose log of the attempt. See [Verbose Log](https://github.com/Ascoware/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a verbose log for your ticket. **Your verbose log should show the results from downloading ONLY ONE program. DO NOT post a massive log covering multiple multiple program downloads. IMPORTANT: DO NOT paste your verbose log into your issue report. If you do, expect it to be deleted.**

If GiA crashes, provide the OS X crash log by copying the information from Crash Reporter into a file or locating the crash log in `$HOME/Library/Logs/DiagnosticReports`. See [Verbose Log](https://github.com/Ascoware/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a crash log for your ticket. **IMPORTANT: DO NOT paste your crash log into your issue report. If you do, expect it to be deleted.**

**Delete the instructions above before submitting your ticket.**

---------------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

*What is the expected output? What do you see instead?*

*What version of GiA are you using? On what version of OS X?*

*Are you using a web proxy? DNS proxy? VPN? VPS?*

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

*Please provide any additional information below.*

**Comment by BritTVfan** [comment]
@skovatch I keep getting a menu that pops up that says "Failed Download Solutions" and it says "problem unknown" whenever I try to download something. It doesn't matter whether it is something on any of the BBC channels or ITV. It's been this way for at least three weeks. Usually I can fool with it or just wait till the next software update, and then I'll be able to get the shows. But for some reason, I can't get anything.

**Comment by skovatch** [comment]
OK, the next thing to try is to go to the Preferences, then click the checkbox that says "Verbose Mode". Then try downloading a show again. You should get more information in the log that will help diagnose what's going on.

**Comment by BritTVfan** [comment]
I checked verbose mode and here is the log:
Get iPlayer Automator 1.14.3 Initialized.
GetITVShows: ITV Cache Update Starting 
<AppController: 0x7fcbcad3a1b0>: Updating Programme Index Feeds...

GetITVShows (Info): Episodes: 1538 Today Programmes: 168 
<AppController: 0x7fcbcad3a1b0>: Index Updated.
GetITVShows: Update Finished


INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads


Downloading Show 1/1:

ITV Download (ID=2a1229a0024): Downloading Endeavour - Sun Feb 10
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.itv.com/hub/endeavour/2a1229a0024", "-f", "mp4/best", "-o", "/Users/sheilaburke/Movies/TV Shows/Endeavour/Endeavour.s06e01.Pylon.%(ext)s", "--verbose"]
DEBUG: youtube-dl environment: ["PATH": "/Applications/Get iPlayer Automator.app/Contents/MacOS:/usr/bin", "PYTHONPATH": "/Applications/Get iPlayer Automator.app/Contents/Resources"]
[debug] System config: []

[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.itv.com/hub/endeavour/2a1229a0024', u'-f', u'mp4/best', u'-o', u'/Users/sheilaburke/Movies/TV Shows/Endeavour/Endeavour.s06e01.Pylon.%(ext)s', u'--verbose']

[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
[debug] youtube-dl version 2018.06.19

[debug] Python version 2.7.10 (CPython) - Darwin-18.2.0-x86_64-i386-64bit

[debug] exe versions: ffmpeg 4.1-tessus, ffprobe N-90346-g86c7d8df95, rtmpdump 2.4-102-ga3a600d-get_iplayer

[debug] Proxy map: {}

[debug] Using fake IP 25.18.191.209 (GB) as X-Forwarded-For.

[ITV] 2a1229a0024: Downloading webpage

[ITV] 2a1229a0024: Downloading XML

WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out

[ITV] 2a1229a0024: Downloading JSON metadata

WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden

ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Traceback (most recent call last):
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/extractor/itv.py", line 259, in _real_extract
    self._sort_formats(formats)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


ITV Download (ID=2a1229a0024): youtube-dl finished downloading
AppController: Downloads Finished

**Comment by skovatch** [comment]
OK, this is helpful. This line
> WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
indicates that you are likely not in the UK. If you were able to download at one point, it likely means your VPN service is no longer working or not configured properly and you need to find a new one.

If you are outside the UK, as a matter of policy I don't help with connectivity issues or VPN setup. There's way too many variables and it's impossible to diagnose that kind of thing long distance. If you are using a VPN service you'll have to research [other options](https://dns4me.net) on your own.

All that said, I think I will update the app to do a better job of reporting what the problem is when this happens.

**Comment by BritTVfan** [comment]
Thank you so much for all your help--and for doing so much work with Get iPlayer Automator!
