### ISSUE TITLE
Unable to download ITV programmes

### ISSUE THREAD

**Issue by xhale** [Ascoware/get-iplayer-automator#253]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Downloading ITV programmes

*What is the expected output? What do you see instead?*
"Problem Unknown.  Please submit a bug report..."

Verbose log:
```
Downloading Show 1/1:

ITV Download (ID=1a7000a0276): Downloading Tour de France - Mon Jul 29
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.itv.com/hub/tour-de-france/1a7000a0276", "-f", "mp4/best", "-o", "/Users/[REMOVED]/Downloads/iPlayer Downloads/Tour de France/Tour de France.s01e23.Episode 23.%(ext)s", "--verbose"]
DEBUG: youtube-dl environment: ["PATH": "/private/var/folders/zs/g10vlmw50sq6y483rvnfn0c00000gn/T/AppTranslocation/DB7796C0-C042-4838-98B7-B5C945748F77/d/Get iPlayer Automator.app/Contents/MacOS:/usr/bin", "PYTHONPATH": "/private/var/folders/zs/g10vlmw50sq6y483rvnfn0c00000gn/T/AppTranslocation/DB7796C0-C042-4838-98B7-B5C945748F77/d/Get iPlayer Automator.app/Contents/Resources"]
[debug] System config: []

[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.itv.com/hub/tour-de-france/1a7000a0276', u'-f', u'mp4/best', u'-o', u'/Users/[REMOVED]/Downloads/iPlayer Downloads/Tour de France/Tour de France.s01e23.Episode 23.%(ext)s', u'--verbose']

[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
[debug] youtube-dl version 2018.06.19

[debug] Python version 2.7.10 (CPython) - Darwin-18.7.0-x86_64-i386-64bit

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main

    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/folders/zs/g10vlmw50sq6y483rvnfn0c00000gn/T/AppTranslocation/DB7796C0-C042-4838-98B7-B5C945748F77/d/Get iPlayer Automator.app/Contents/Resources/youtube-dl/__main__.py", line 19, in <module>

  File "/var/folders/zs/g10vlmw50sq6y483rvnfn0c00000gn/T/AppTranslocation/DB7796C0-C042-4838-98B7-B5C945748F77/d/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/__init__.py", line 472, in main
  File "/var/folders/zs/g10vlmw50sq6y483rvnfn0c00000gn/T/AppTranslocation/DB7796C0-C042-4838-98B7-B5C945748F77/d/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/__init__.py", line 439, in _real_main

  File "/var/folders/zs/g10vlmw50sq6y483rvnfn0c00000gn/T/AppTranslocation/DB7796C0-C042-4838-98B7-B5C945748F77/d/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/YoutubeDL.py", line 417, in __init__
  File "/var/folders/zs/g10vlmw50sq6y483rvnfn0c00000gn/T/AppTranslocation/DB7796C0-C042-4838-98B7-B5C945748F77/d/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/YoutubeDL.py", line 2260, in print_debug_header

  File "/var/folders/zs/g10vlmw50sq6y483rvnfn0c00000gn/T/AppTranslocation/DB7796C0-C042-4838-98B7-B5C945748F77/d/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 76, in get_versions
  File "/var/folders/zs/g10vlmw50sq6y483rvnfn0c00000gn/T/AppTranslocation/DB7796C0-C042-4838-98B7-B5C945748F77/d/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 60, in __init__

  File "/var/folders/zs/g10vlmw50sq6y483rvnfn0c00000gn/T/AppTranslocation/DB7796C0-C042-4838-98B7-B5C945748F77/d/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 117, in _determine_executables
  File "/var/folders/zs/g10vlmw50sq6y483rvnfn0c00000gn/T/AppTranslocation/DB7796C0-C042-4838-98B7-B5C945748F77/d/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 117, in <genexpr>

  File "/var/folders/zs/g10vlmw50sq6y483rvnfn0c00000gn/T/AppTranslocation/DB7796C0-C042-4838-98B7-B5C945748F77/d/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/utils.py", line 1962, in get_exe_version
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    
child_exception = pickle.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"

ValueError: insecure string pickle

ITV Download (ID=1a7000a0276): youtube-dl finished downloading
AppController: Downloads Finished
```

*What version of GiA are you using? On what version of OS X?*
GIA 1.15.2
macOS 10.14.6

*Are you using a web proxy? DNS proxy? VPN? VPS?*
No, UK based

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
Tour de France - Mon Jul 29 from ITV

**Comment by skovatch** [comment]
Might be time for a new YouTube-dl. I think I tried an ITV download, and it succeeded, but there were 'problem unknown' issues; I thought my drive was full.

I'll take a look.

**Comment by skovatch** [comment]
I'm downloading ITV shows now, and have essentially the same configuration as you, though I'm now using GiA 1.16. That shouldn't have affected ITV/youtube-dl, so I'm wondering if this was a one-time problem. Is it still an issue for you?

The error indicates that youtube-dl is failing to get the version information of ffmpeg. Please download a fresh copy of GiA from https://github.com/Ascoware/get-iplayer-automator/releases and see if that helps matters.

**Comment by xhale** [comment]
Downloaded 1.16 and still fails at the same point.  BBC downloads are fine.

**Comment by strafer** [comment]
Yes, ITV downloads are still broken, with or without a VPN. I'm in North America. Error message as follows:

`[debug] Using fake IP 25.82.177.181 (GB) as X-Forwarded-For.
[ITV] 2a1873a0037: Downloading webpage
[ITV] 2a1873a0037: Downloading XML
WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[ITV] 2a1873a0037: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/itv.py", line 260, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by skovatch** [comment]
> Yes, ITV downloads are still broken, with or without a VPN. I'm in North America. Error message as follows:
> 
> > [debug] Using fake IP 25.82.177.181 (GB) as X-Forwarded-For.
> > [ITV] 2a1873a0037: Downloading webpage
> > [ITV] 2a1873a0037: Downloading XML
> > WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
> > [ITV] 2a1873a0037: Downloading JSON metadata
> > **WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden

A 403 error indicates your VPN service is no longer working or that ITV has otherwise detected you aren't in the UK. This is not a GiA or youtube-dl issue.

**Comment by strafer** [comment]
> > Yes, ITV downloads are still broken, with or without a VPN. I'm in North America. Error message as follows:
> > > [debug] Using fake IP 25.82.177.181 (GB) as X-Forwarded-For.
> > > [ITV] 2a1873a0037: Downloading webpage
> > > [ITV] 2a1873a0037: Downloading XML
> > > WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
> > > [ITV] 2a1873a0037: Downloading JSON metadata
> > > **WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
> 
> A 403 error indicates your VPN service is no longer working or that ITV has otherwise detected you aren't in the UK. This is not a GiA or youtube-dl issue.

Well damn. I'm guess I'm SOL if ITV can detect my VPN, regardless of which UK server I use.

**Comment by xhale** [comment]
@skovatch Noticed GIA 1.16.1 had been released since I last tried an ITV download.  Upgraded from 1.16 just now and successfully downloaded an ITV show.  Don't know if you changed anything or whether it was something on my side all along, but anyway thanks for your work on the project!

**Comment by skovatch** [comment]
youtube-dl was updated between 1.16 and 1.16.1, so that might be the difference, though I didn't see anything in particular that would have fixed that. But good to know it works now!
