### ISSUE TITLE
Unable to download specific ITV episode (Unforgotten, s04e05)

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#317]
**What steps will reproduce the problem?**
I am having a specific problem with a particular ITV episode which downloads fine using Downie.
Other shows on ITV are OK.

**What is the expected output? What do you see instead?**
**expect:** Download completed
**get:** Status: Download failed

**What version of GiA are you using? On what version of OS X?**
GiA: 1.21.4
macOS: 11.2.3

**Are you using a web proxy? DNS proxy? VPN? VPS?**
No.

**What program are you attempting to download (full title, series and episode)?**
Unforgotten - s04e05

**Logs:**
```
Get iPlayer Automator 1.21.4 Initialized.
GetITVShows: ITV Cache Update Starting 
<AppController: 0x7fba20746390>: Updating Programme Index Feeds...

INFO: Indexing tv programmes (concurrent)
GetITVShows (Info): Episodes: 3211 Today Programmes: 311 
GetITVShows: Update Finished
INFO: Added 39 tv programmes to cache
INFO: 8501 matching programmes
<AppController: 0x7fba20746390>: Index Updated.


INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads


Downloading Show 1/1:

Downloading Unforgotten: Season 4
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
youtube-dl finished downloading
AppController: Downloads Finished
```

**Comment by WilliamOfGaunt** [comment]
I had problems downloading this as well - last night it failed partway through (but I failed to keep the log), and again this morning (edited log below), but when I ran the download again from where it had left off it completed successfully. 

~~~~~~~~~ [Edited logfile below] ~~~~~~~~~~

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads


Downloading Show 1/3:

Downloading Unforgotten: Season 4
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.itv.com/hub/unforgotten/2a3372a0023", "-f", "mp4/best", "-o", "/Users/bruce/Desktop/get_iplayer Downloads/Unforgotten - Season 4/Unforgotten - Season 4.s04e23.Episode 5.%(ext)s", "--verbose"]
DEBUG: youtube-dl environment: ["PYTHONPATH": "/Applications/Get iPlayer Automator.app/Contents/Resources", "PATH": "/Applications/Get iPlayer Automator.app/Contents/MacOS:/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer/utils/bin:/usr/bin"]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.itv.com/hub/unforgotten/2a3372a0023', u'-f', u'mp4/best', u'-o', u'/Users/bruce/Desktop/get_iplayer Downloads/Unforgotten - Season 4/Unforgotten - Season 4.s04e23.Episode 5.%(ext)s', u'--verbose']
[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
[debug] youtube-dl version 2020.12.12
[debug] Python version 2.7.16 (CPython) - Darwin-20.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2-tessus
[debug] Proxy map: {}
[debug] Using fake IP 25.77.64.52 (GB) as X-Forwarded-For.
[ITV] 2a3372a0023: Downloading webpage
[ITV] 2a3372a0023: Downloading JSON metadata
[ITV] 2a3372a0023: Downloading m3u8 information
[debug] Invoking downloader on u'https://itvpnpdotcom.content.itv.com/2-3372-0023-001/18/2/VAR012/2-3372-0023-001_18_2_VAR012.ism/2-3372-0023-001_18_2_VAR012-audio=128000-video=1425215.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 461
[download] Destination: /Users/bruce/Desktop/get_iplayer Downloads/Unforgotten - Season 4/Unforgotten - Season 4.s04e23.Episode 5.mp4
Downloading to /Users/bruce/Desktop/get_iplayer Downloads/Unforgotten - Season 4/Unforgotten - Season 4.s04e23.Episode 5.mp4
[download]   0.0% of ~502.70MiB at Unknown speed ETA 13:13:14
[download]   0.0% of ~502.70MiB at Unknown speed ETA 04:24:57
[download]   0.0% of ~502.70MiB at Unknown speed ETA 01:53:46
[download]   0.0% of ~502.70MiB at Unknown speed ETA 53:11
[download]   0.0% of ~502.70MiB at 28.29MiB/s ETA 25:48
[download]   0.0% of ~502.70MiB at 23.74MiB/s ETA 12:54

... [many lines omitted] ...

[download]  50.3% of ~539.46MiB at 20.52MiB/s ETA 00:32
ERROR: unable to download video data: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:727)>
Traceback (most recent call last):
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/YoutubeDL.py", line 1936, in process_info
    success = dl(filename, info_dict)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/YoutubeDL.py", line 1875, in dl
    return fd.download(name, info)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/downloader/hls.py", line 148, in real_download
    ctx, frag_url, info_dict, headers)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/downloader/fragment.py", line 104, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
URLError: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:727)>
youtube-dl finished downloading

**Comment by jchhenderson** [comment]
yes, it has just worked for me as well.

```
Get iPlayer Automator 1.21.4 Initialized.
GetITVShows: ITV Cache Update Starting 
<AppController: 0x7fba13529430>: Updating Programme Index Feeds...

INFO: Indexing tv programmes (concurrent)
GetITVShows (Info): Episodes: 3219 Today Programmes: 311 
GetITVShows: Update Finished
INFO: Added 0 tv programmes to cache
INFO: 8497 matching programmes
<AppController: 0x7fba13529430>: Index Updated.


INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads


Downloading Show 1/3:

Downloading Unforgotten: Season 4
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
youtube-dl finished downloading
```

**Comment by skovatch** [comment]
I downloaded it just now without any issues, other than the random 403 error at startup.

The TLSV1 error looks like a hiccup of some kind in the SSL connection. It will be a youtube-dl problem, in any event.

**Comment by skovatch** [comment]
I'll close this for now but if we see a pattern we can reopen it.

**Comment by jefro108** [comment]
Random errors in download for the same episode as well as latest episodes of Plebs. Took ages repeated pressing Start queue button - and occasionally stopping because it got stuck getting the metadata file. Possible internet connection problem at the time. See complete log file at https://gist.github.com/jefro108/be842f960fe9b8da7eb2e9ea23b9863a
