### ISSUE TITLE
ITV Download Failure

### ISSUE THREAD

**Issue by sxmpete** [Ascoware/get-iplayer-automator#363]
Cannot DL Endeavour from ITV.
GIA 1.21.12 Mac OS Mojave, iMac.
This is same failure reported in September, see attached log.
[ITV Download Fail 28Nov2021.docx](https://github.com/Ascoware/get-iplayer-automator/files/7613689/ITV.Download.Fail.28Nov2021.docx)

**Comment by jphiller** [comment]
Same issue on any ITV program.  Any program attempted errors as follows, and not related to blocked IP, at least by logs:

`[download]  50.2% of ~566.91MiB at 955.83KiB/s ETA 25:51
ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:727)>
Traceback (most recent call last):
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/YoutubeDL.py", line 1967, in process_info
    success = dl(filename, info_dict)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/YoutubeDL.py", line 1906, in dl
    return fd.download(name, info)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/downloader/hls.py", line 150, in real_download
    ctx, frag_url, info_dict, headers)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/downloader/fragment.py", line 104, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:727)>
youtube-dl finished downloading
AppController: Downloads Finished
`

**Comment by SOLOSAIR** [comment]
GiA ITV not going past the 'downloading...' stage on Coronation Street or Bradley & Barney Walsh: Breaking Dad: Series 4'

Have ITV changed the goalposts again?

**Comment by Mac-Man-APH** [comment]
Same issue here BBC fine ITV stuck on 'Downloading...'., was all OK last week. Using latest GiA and Big Sur versions.

Andrew

**Comment by SOLOSAIR** [comment]
ITV - NO DOWNLOADS POSSIBLE
GiA - Every ITV programme I try to download gets stuck on 'downloading...' Not a continuation of a previous part-download. This getting stuck happens with PVR listed series *and* with using 'use current webpage'.   I have also tried 'process PID' button without success. Tonight's download try is 'Ghislaine, Prince Andrew and the Paedophile' This is the 3rd show I have tried over 2 nights which is stuck on 'downloading'. I have not changed any settings.

macOS Monterey 12.1
GiA 1.21.12 (20210729001)

**Comment by Mac-Man-APH** [comment]
Just checked GiA again and ITV Hub download works fine (Midsomer Murders) but ITV still still not playing ball.

**Comment by Mac-Man-APH** [comment]
Tried another download again today and GiA failed this time accessing ITV Hub, 2 different episodes of Midsomer Murders from yesterday, as well all fails with ITV.

**Comment by Rock-Hunter** [comment]
I never download anything off ITV but out of interest thought I'd give it a try. I just successfully downloaded the latest episode of Emmerdale along with a documentary about Maxwell. I'm in the UK and not using a VPN, my mac is running on Catalina 10.15.7.

Hope this helps and good luck.

**Comment by skovatch** [comment]
Should be fixed in v1.21.13
